dist: trusty
language: node_js
addons:
  chrome: stable
notifications:
  email: false
node_js: lts/*
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test:ci
        - npm run build
        - npm run test:report
      before_deploy:
        - npm run pack
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
        on:
          tags: false
          all_branches: true
          condition: '$TRAVIS_BRANCH =~ ^(master)$'
